name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install QGIS
        run: |
          sudo apt update
          sudo apt install -y gnupg software-properties-common
          sudo wget -O /etc/apt/keyrings/qgis-archive-keyring.gpg https://download.qgis.org/downloads/qgis-archive-keyring.gpg
          sudo cat << EOF > /etc/apt/sources.list.d/qgis.sources
          Types: deb deb-src
          URIs: https://qgis.org/debian
          Suites: bookworm
          Architectures: amd64
          Components: main
          Signed-By: /etc/apt/keyrings/qgis-archive-keyring.gpg
          EOF
          sudo apt update
          sudo apt install -y qgis
          qgis_process
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - uses: julia-actions/cache@v2
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: julia --project=docs/ docs/make.jl
